-- Supabase Database Schema for mawlid_al_dhaki app
-- Run this in your Supabase SQL Editor

-- Subscribers table
CREATE TABLE IF NOT EXISTS subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE NOT NULL,
  cabinet TEXT NOT NULL,
  phone TEXT NOT NULL,
  status BIGINT NOT NULL DEFAULT 1,
  start_date TIMESTAMP NOT NULL,
  accumulated_debt REAL DEFAULT 0,
  tags TEXT,
  notes TEXT,
  last_modified TIMESTAMP,
  last_synced_at TIMESTAMP,
  sync_status TEXT DEFAULT 'local_only',
  dirty_flag BOOLEAN DEFAULT false,
  cloud_id TEXT,
  deleted_locally BOOLEAN DEFAULT false,
  permissions_mask TEXT,
  conflict_origin TEXT,
  conflict_detected_at TIMESTAMP,
  conflict_resolved_at TIMESTAMP,
  conflict_resolution_strategy TEXT,
  last_sync_error TEXT,
  sync_retry_count BIGINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Payments table
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscriber_id BIGINT NOT NULL REFERENCES subscribers(id),
  amount REAL NOT NULL,
  worker TEXT NOT NULL,
  date TIMESTAMP NOT NULL,
  cabinet TEXT NOT NULL,
  last_modified TIMESTAMP,
  last_synced_at TIMESTAMP,
  sync_status TEXT DEFAULT 'local_only',
  dirty_flag BOOLEAN DEFAULT false,
  cloud_id TEXT,
  deleted_locally BOOLEAN DEFAULT false,
  permissions_mask TEXT,
  conflict_origin TEXT,
  conflict_detected_at TIMESTAMP,
  conflict_resolved_at TIMESTAMP,
  conflict_resolution_strategy TEXT,
  last_sync_error TEXT,
  sync_retry_count BIGINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Workers table
CREATE TABLE IF NOT EXISTS workers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  permissions TEXT NOT NULL,
  today_collected REAL DEFAULT 0,
  month_total REAL DEFAULT 0,
  last_modified TIMESTAMP,
  last_synced_at TIMESTAMP,
  sync_status TEXT DEFAULT 'local_only',
  dirty_flag BOOLEAN DEFAULT false,
  cloud_id TEXT,
  deleted_locally BOOLEAN DEFAULT false,
  permissions_mask TEXT,
  conflict_origin TEXT,
  conflict_detected_at TIMESTAMP,
  conflict_resolved_at TIMESTAMP,
  conflict_resolution_strategy TEXT,
  last_sync_error TEXT,
  sync_retry_count BIGINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Cabinets table
CREATE TABLE IF NOT EXISTS cabinets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  total_subscribers BIGINT NOT NULL,
  current_subscribers BIGINT NOT NULL,
  collected_amount REAL DEFAULT 0,
  delayed_subscribers BIGINT DEFAULT 0,
  completion_date TIMESTAMP,
  last_modified TIMESTAMP,
  last_synced_at TIMESTAMP,
  sync_status TEXT DEFAULT 'local_only',
  dirty_flag BOOLEAN DEFAULT false,
  cloud_id TEXT,
  deleted_locally BOOLEAN DEFAULT false,
  permissions_mask TEXT,
  conflict_origin TEXT,
  conflict_detected_at TIMESTAMP,
  conflict_resolved_at TIMESTAMP,
  conflict_resolution_strategy TEXT,
  last_sync_error TEXT,
  sync_retry_count BIGINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Audit Log table
CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" TEXT NOT NULL,
  action TEXT NOT NULL,
  target TEXT NOT NULL,
  details TEXT,
  type TEXT NOT NULL,
  timestamp TIMESTAMP DEFAULT NOW(),
  last_modified TIMESTAMP,
  last_synced_at TIMESTAMP,
  sync_status TEXT DEFAULT 'local_only',
  dirty_flag BOOLEAN DEFAULT false,
  cloud_id TEXT,
  deleted_locally BOOLEAN DEFAULT false,
  permissions_mask TEXT,
  conflict_origin TEXT,
  conflict_detected_at TIMESTAMP,
  conflict_resolved_at TIMESTAMP,
  conflict_resolution_strategy TEXT,
  last_sync_error TEXT,
  sync_retry_count BIGINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- WhatsApp Templates table
CREATE TABLE IF NOT EXISTS whatsapp_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  isActive BOOLEAN DEFAULT true,
  last_modified TIMESTAMP,
  last_synced_at TIMESTAMP,
  sync_status TEXT DEFAULT 'local_only',
  dirty_flag BOOLEAN DEFAULT false,
  cloud_id TEXT,
  deleted_locally BOOLEAN DEFAULT false,
  permissions_mask TEXT,
  conflict_origin TEXT,
  conflict_detected_at TIMESTAMP,
  conflict_resolved_at TIMESTAMP,
  conflict_resolution_strategy TEXT,
  last_sync_error TEXT,
  sync_retry_count BIGINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Generator Settings table
CREATE TABLE IF NOT EXISTS generator_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  address TEXT NOT NULL,
  logo_path TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_subscribers_code ON subscribers(code);
CREATE INDEX IF NOT EXISTS idx_subscribers_cabinet ON subscribers(cabinet);
CREATE INDEX IF NOT EXISTS idx_subscribers_status ON subscribers(status);
CREATE INDEX IF NOT EXISTS idx_payments_subscriber_id ON payments(subscriber_id);
CREATE INDEX IF NOT EXISTS idx_payments_date ON payments(date);
CREATE INDEX IF NOT EXISTS idx_payments_worker ON payments(worker);
CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON audit_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_log_user ON audit_log("user");
CREATE INDEX IF NOT EXISTS idx_whatsapp_templates_active ON whatsapp_templates(is_active);
